version: '3.8'

services:
  web:  # <-- "web" muss unter "services:" stehen
    build: .
    container_name: wetteranwendung
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1GB"
