name: Test, Build & Push Docker Image to GHCR

on:
  push:
    branches:
      - main
      - branch-LucaSchneider
      - branch-leon
      - branch-tim

jobs:
  test:
    name: Run Tests before Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Django Tests
        run: |
          python manage.py test

  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install frontend dependencies
        run: npm install
      - name: Run Frontend Tests
        run: npm test

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_BUILD_DOCKER_IMAGE_AND_PUSH_TO_GHCR }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/dhbw-projekt-anwendungsentwicklung/wetteranwendung:latest, ghcr.io/dhbw-projekt-anwendungsentwicklung/wetteranwendung:${{ github.ref_name }}

